[tool.poetry]
name = "krux-file-signer"
version = "0.0.1"
description = "A python script to sign files and verify signatures in a airgapped manner"
authors = [
  "odudex <eduardo.schoenknecht@gmail.com>",
  "qlrddev <qlrddev@gmail.com>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<=3.11.5"
opencv-python = "^4.8.0.76"
qrcode = "^7.4.2"
pillow = "^10.0.1"
pyzbar = "^0.1.9"
kivy = "^2.2.1"
pyqrcode = "^1.2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
pylint = "^2.17.5"
pyinstaller = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
